name: simple_dart_radio_field
description: RadioField Component
version: 0.0.4
repository: https://github.com/simple-dart/radio_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_label: ^0.0.1
  simple_dart_ui_core: ^0.0.4

